# Test your FastAPI endpoints


POST http://127.0.0.1:8000/login/ment/
Content-Type: application/json

{
    "email": "pidoras@gmail.com",
    "password": "сосузавзтку"
}

###

POST http://127.0.0.1:8000/register/lil/
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImViYWx2ZnNocm90QG1haWwucnUiLCJyYW5rIjoiXHUwNDNmXHUwNDNlXHUwNDNiXHUwNDNhXHUwNDNlXHUwNDMyXHUwNDNkXHUwNDM4XHUwNDNhIiwiZGVwX2lkIjoxLCJleHAiOjE3MTU1Mzc3Mjh9.tB_do6KdMb0dqyJZ6_7ON54ATxJjkw6UTx2XbdlGO48",
    "id": 2,
    "fio": "Дипор Д.Р.",
    "rank": "lil",
    "experience": 7,
    "age": 29,
    "dep_id": 1,
    "boss": 1,
    "email": "pidoras@gmail.com",
    "password": "сосузавзтку"
}


###


GET http://127.0.0.1:8000/get/gai/1
Accept: application/json


###


GET http://127.0.0.1:8000/get/ment/1
Accept: application/json


###


POST http://127.0.0.1:8000/register/user/
Content-Type: application/json

{
  "fio": "Корпенко А.В.",
  "license": 243672423,
  "card": 2341437273,
  "email": "noejv@mgni.com",
  "password": "nfjunijnnbnwkj"
}

###

POST http://127.0.0.1:8000/login/user/
Content-Type: application/json

{
  "email": "noejv@mgni.com",
  "password": "nfjunijnnbnwkj"
}

###

POST http://127.0.0.1:8000/get/user/data
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpZG9yYXNAZ21haWwuY29tIiwicmFuayI6Ilx1MDQzY1x1MDQzMFx1MDQzOVx1MDQzZVx1MDQ0MCIsImRlcF9pZCI6MSwiZXhwIjoxNzE1ODEwNDAwfQ.lbdsYZAPzC_HHBHKjG5j4i-Dd5uJSRE4YkmSOUVEfHk",
  "license": 243672423
}

###

POST http://127.0.0.1:8000/add/car/
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjQzNjcyNDIzLCJmaW8iOiJcdTA0MWFcdTA0M2VcdTA0NDBcdTA0M2ZcdTA0MzVcdTA0M2RcdTA0M2FcdTA0M2UgXHUwNDEwLlx1MDQxMi4iLCJsaWNlbnNlIjoyMzQxNDM3MjczLCJjYXJkIjpbIm5vZWp2QG1nbmkuY29tIl0sInJhbmsiOiJ1c2VyIiwiZXhwIjoxNzE1ODEwNDAwfQ.Z6ClkXpebH3iipQIPOhxK-JIvVLs7VxtkXl25FIAmGQ",
  "car_num": "a348пт777",
  "pts": 7234863248,
  "insurance": 2374798734,
  "id_user": 243672423
}

###

GET http://127.0.0.1:8000/get/user/car/A348HT777
Accept: application/json
